# Generated by Django 2.2 on 2021-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210304_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Значение')),
                ('color', models.CharField(choices=[('Оранжевый', 'tags__checkbox_style_orange'), ('Зеленый', 'tags__checkbox_style_green'), ('Фиолетовый', 'tags__checkbox_style_purple')], max_length=10, verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag'),
        ),
    ]
