# Generated by Django 2.2 on 2021-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210305_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('tags__checkbox_style_orange', 'Оранжевый'), ('tags__checkbox_style_green', 'Зеленый'), ('tags__checkbox_style_purple', 'Фиолетовый')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
